//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resumes
    {
        public int ResumeID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string SchoolName { get; set; }
        public Nullable<System.DateTime> GraduationDate { get; set; }
        public string Degree { get; set; }
        public string CompanyName { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> EmploymentStartDate { get; set; }
        public Nullable<System.DateTime> EmploymentEndDate { get; set; }
        public string Responsibilities { get; set; }
        public string Skills { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public string TechnologiesUsed { get; set; }
        public string CertificationName { get; set; }
        public Nullable<System.DateTime> CertificationDate { get; set; }
        public string ForeignLanguage { get; set; }
        public string Hobbies { get; set; }
        public string ReferencePerson { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
